
# ON
set(MSDFGEN_CORE_ONLY ON CACHE BOOL "MSDFGEN_CORE_ONLY" FORCE)
set(MSDFGEN_USE_OPENMP ON CACHE BOOL "MSDFGEN_USE_OPENMP" FORCE)
set(MSDFGEN_USE_CPP11 ON CACHE BOOL "MSDFGEN_USE_CPP11" FORCE)

# OFF
set(MSDFGEN_BUILD_STANDALONE OFF CACHE BOOL "MSDFGEN_BUILD_STANDALONE" FORCE)
set(MSDFGEN_USE_VCPKG OFF CACHE BOOL "MSDFGEN_USE_VCPKG" FORCE)
set(MSDFGEN_USE_SKIA OFF CACHE BOOL "MSDFGEN_USE_SKIA" FORCE)
set(MSDFGEN_INSTALL OFF CACHE BOOL "MSDFGEN_INSTALL" FORCE)
set(MSDFGEN_DYNAMIC_RUNTIME OFF CACHE BOOL "MSDFGEN_DYNAMIC_RUNTIME" FORCE)
set(BUILD_SHARED_LIBS OFF CACHE BOOL "BUILD_SHARED_LIBS" FORCE)

add_subdirectory(${CMAKE_SOURCE_DIR}/3rdparty/msdfgen)

#file(GLOB_RECURSE CORE_RECURSE 
#	${MSDFGEN_INCLUDE_DIR}/core/*.*)
#source_group(TREE ${MSDFGEN_INCLUDE_DIR}/core PREFIX src/core FILES ${CORE_RECURSE})

#file(GLOB_RECURSE EXT_RECURSE 
#	${MSDFGEN_INCLUDE_DIR}/ext/*.*)
#source_group(TREE ${MSDFGEN_INCLUDE_DIR}/ext PREFIX src/ext FILES ${EXT_RECURSE})

#file(GLOB SRC_RECURSE 
#	${MSDFGEN_INCLUDE_DIR}/msdfgen.h)
#source_group(TREE ${MSDFGEN_INCLUDE_DIR} PREFIX src FILES ${SRC_RECURSE})

#add_library(msdfgen STATIC 
#	${SRC_RECURSE}
#	${CORE_RECURSE}
#	#${EXT_RECURSE}
#)

set(MSDFGEN_INCLUDE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/3rdparty/msdfgen)
set(MSDFGEN_LIBRARIES msdfgen-core)

set_target_properties(${MSDFGEN_LIBRARIES} PROPERTIES FOLDER 3rdparty/Static)

