if (USE_GPU_METRIC)
	if(WIN32)
		message("GPU METRIC id enabled, but only with the couple NVIDIA && Windows")
		add_definitions(-DUSE_GPU_METRIC)
		set(NVAPI_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/3rdparty/NVApi_R470)
		if ("${CMAKE_EXE_LINKER_FLAGS}" STREQUAL "/machine:x64")
			set(NVAPI_LIBRARIES ${NVAPI_INCLUDE_DIR}/amd64/nvapi64.lib)
		else()
			set(NVAPI_LIBRARIES ${NVAPI_INCLUDE_DIR}/x86/nvapi.lib)
		endif()
	endif()
endif()