name: Linux

on:
  push:
    branches:
    - master

jobs:
  build_Linux_Ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: master
    - name: checkout submodules
      run : git submodule update --init --recursive 
    - name: Install OpenGL lib  / Requirement for Glfw3
      run : sudo apt-get update && sudo apt-get install libgl1-mesa-dev libx11-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev
    - name: configure
      run: mkdir build && cd build && cmake .. -DCMAKE_BUILD_TYPE=Release -DUSE_VR=OFF -DUSE_GPU_METRIC=OFF
    - name: build
      run: cmake --build build
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: NoodlesPlate_Linux_x64
        path: build/Release/NoodlesPlate_Linux_x64
